"use strict";

const VERTEX_DATA_TYPE = 0;
const VERTEX_DATA_SIDE = 1;
const VERTEX_DATA_SHADE = 2;
const VERTEX_DATA_COLOUR = 3;

export default {
  VERTEX_DATA_TYPE,
  VERTEX_DATA_SIDE,
  VERTEX_DATA_SHADE,
  VERTEX_DATA_COLOUR
};
