"use strict";

/**
 * These values are deltas generated by the UI. Values of 0 mean nothing is changing and the player is still
 */
export interface Movement {
  move: THREE.Vector3;
  turn: THREE.Vector2;
}
